### ISSUE TITLE
Hide irrelevant anime improvements 

### ISSUE THREAD

**Issue by Josh-Star** [matt4682/Shinjiru#3]
At the moment the torrent hide irrelevant anime check box hides anything that isn't on your list. However I have things like Shigatsu wa Kimi no Uso on hold, and Fairy Tail (2014) dropped but they still appear in the torrent list. 

Making it so only shows that have the watching or plan to watch status would be ideal.

Also any list items that are default hidden won't show up on the torrent list but thats something more for when custom list are properly supported.

**Comment by matt4682** [comment]
It should only show watching/ptw in update 0.1.1 once I finish rolling it out.

**Comment by Josh-Star** [comment]
Okay thanks :)
