### ISSUE TITLE
Use smaller image for user avatar

### ISSUE THREAD

**Issue by Josh-Star** [matt4682/Shinjiru#6]
Minor issue but the down scaling of the user avatar looks pretty bad:

![](http://puu.sh/eondn/dbce65088f.png)

Unless you really want animated gif supported maybe it would be best to use one of the smaller avatar images.

**Comment by matt4682** [comment]
It's actually using image_url_med which is the smallest avatar image available.

I've made some adjustments to how the image is drawn and it looks much better now.

![old](http://i.imgur.com/DZflfWD.png) -> ![new](http://i.imgur.com/9U1wsmv.png)
