### ISSUE TITLE
Missing anime cover images

### ISSUE THREAD

**Issue by Josh-Star** [matt4682/Shinjiru#8]
I noticed on the features page of the site that the airing page and anime information panel both have anime cover images.

I don't seem to have any images though:
![](http://puu.sh/ez18n/3140471c14.png)

![](http://puu.sh/ez1eR/6611b1b817.png)

**Comment by Josh-Star** [comment]
Was talking to some users on the AniList irc, seem to have a similar issue:
`<BrianJohnston> does anyone else have a couple random covers showing up in airing instead of none?`

![](http://i.imgur.com/Rymu2Tw.png)

**Comment by matt4682** [comment]
Huh, for some reason apps deployed with QT only support png out of the box. Which explains why your profile picture is showing.

I tossed in the .dlls for jpeg and gif in an update so that should fix them up.

**Comment by Josh-Star** [comment]
Yep thats fixed it thanks for the quick update :)
